apiVersion: v1
kind: Namespace
metadata:
  name: wordpress-namespace
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: wordpress-namespace
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: wordpress-pod
  namespace: wordpress-namespace
  labels:
    app: wordpress
spec:
  containers:
    - name: wordpress-container
      image: wordpress:latest
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: wordpress-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: wordpress-namespace
data:
  WORDPRESS_DB_HOST: "mysql-service"
  WORDPRESS_DB_USER: "wordpress_user"
  WORDPRESS_DB_PASSWORD: "password"
  WORDPRESS_DB_NAME: "wordpress_db"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: wordpress-namespace
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: wordpress-namespace
  labels:
    app: mysql
spec:
  containers:
    - name: mysql-container
      image: mysql:5.7
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: mysql-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: wordpress-namespace
data:
  MYSQL_ROOT_PASSWORD: "password"
  MYSQL_USER: "wordpress_user"
  MYSQL_PASSWORD: "password"
  MYSQL_DATABASE: "wordpress_db"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ingress
  namespace: wordpress-namespace
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress-service
                port:
                  number: 80
